version: ${version}
name: ${plugin.name}
main: ${plugin.main}
description: ${plugin.description}
author: ${plguin.author}
website: ${plugin.website}
database: ${plugin.database}

commands:
  lifegame:
    aliases: lg